### ISSUE TITLE
Edited todo does not get saved

### ISSUE THREAD

**Issue by ToDo-User** [1N0T/ToDo-AngularJs#1]
Edited todo content is lost after browser refresh. I investigated and i am guessing:

```
$scope.modificarTarea = function ( tarea )
```

Needs some additional logic. I added:

```
almacenamientoLocal.put("pendientes", $scope.tareasPendientes);
almacenamientoLocal.put("activas", $scope.tareasActivas);
```

After:

```
$scope.indiceActual = 0;
$scope.tarea = "";
$scope.modo  = "añadir";
```

And it looks like everything works OK and edited todo is saved. Than you for making this project as i use it for personal stuff and it does the job great!

**Comment by 1N0T** [comment]
Yes, you are right. I added the persistence in the switch statement.
