### ISSUE TITLE
'TypeError: undefined is not a function' fixed. 

### ISSUE THREAD

**Issue by ToDo-User** [1N0T/ToDo-AngularJs#2]
Before i forget i noticed this error detected in JS console at run time for provided ui-tinymce library and there is an easy fix:

https://github.com/angular-ui/ui-tinymce/pull/111/files?diff=split

I didn't detect any issues with ToDo list because of this error but as the fix is trivial i reported it to fix the error report itself at ToDo-AngularJs initiation time.

**Comment by 1N0T** [comment]
Your solution only work with JQuery. I replaced by
elm.triggerHandler('blur');
